# Generated by Django 2.1.7 on 2019-03-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='权重'),
        ),
    ]
