# Generated by Django 2.1.7 on 2019-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='卡片名称')),
                ('picture', models.ImageField(upload_to='card', verbose_name='图标')),
                ('link', models.URLField(blank=True, null=True, verbose_name='超链接')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('numbers', models.BigIntegerField(default=0, editable=False, verbose_name='点击量')),
                ('tag', models.ManyToManyField(to='tag.Tag', verbose_name='卡片标签')),
            ],
            options={
                'verbose_name': '导航卡片',
                'verbose_name_plural': '导航卡片',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='菜单名')),
                ('link', models.URLField(verbose_name='超链接')),
            ],
            options={
                'verbose_name': '卡片底部菜单',
                'verbose_name_plural': '卡片底部菜单',
            },
        ),
    ]
