# Generated by Django 2.1.7 on 2019-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='card',
            name='weight',
            field=models.IntegerField(default=0, help_text='数值越大越靠前', verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
