# Generated by Django 2.1.7 on 2019-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20190329_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0, help_text='数值越大越靠前', verbose_name='权重'),
        ),
    ]
